on: [push, pull_request]

name: Continuous integration

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      
      - name: Run cargo check for i8080
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --manifest-path i8080/Cargo.toml

      - name: Run cargo check for space-invaders
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --manifest-path space-invaders/Cargo.toml

  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Install sdl2
        run: sudo apt-get install libsdl2-dev

      - name: Run cargo test for i8080
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path i8080/Cargo.toml

      - name: Run cargo test for space-invaders
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path space-invaders/Cargo.toml

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Install rustfmt
        run: rustup component add rustfmt

      - name: Run cargo fmt for i8080
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --manifest-path i8080/Cargo.toml --all -- --check

      - name: Run cargo fmt for space-invaders
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --manifest-path space-invaders/Cargo.toml --all -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Install clippy
        run: rustup component add clippy

      - name: Run cargo clippy for i8080
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --manifest-path i8080/Cargo.toml -- -D warnings

      - name: Run cargo clippy for space-invaders
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --manifest-path space-invaders/Cargo.toml -- -D warnings
